version: '3'

services:
  backend:
    container_name: django
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    tty: true
    command:
      python manage.py runserver 0.0.0.0:8000
      
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./dockerfiles/nuxt/Dockerfile
    tty: true
    # 初回のみ yarn install するようにする
    # 参考: https://genzouw.com/entry/2021/04/28/215832/2563/
    entrypoint:
      - sh
    command:
      - -c
      - |
        cd scraper
        [ -f ./.yarn-install-once ] || {
          yarn install && touch ./.yarn-install-once
        }
        yarn dev
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/scraper/node_modules
    ports:
      - "3000:3000"
volumes:
  node_modules_volume:
