version: '3'

services:
  backend:
    container_name: django
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    tty: true
    command:
      python manage.py runserver 0.0.0.0:8000
      
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./dockerfiles/nuxt/Dockerfile
    tty: true
    command:
      sh -c '
        cd scraper &&
        yarn dev'
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"